server:
  port: 1258
  tomcat:
    threads:
      max: 2000
    max-connections: 10000

#logging:
#  level:
#    com.netsec.sm: debug
spring:
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
springdoc:
  swagger-ui:
    path: /api.html
    enabled: true
logging:
  level:
    com.netsec.sm: off
